-- Creative Builder: Interactive image prompt constructor
-- Adds creative_builder_state column to news table
-- Creates creative_elements table with seed data
-- Adds AI prompt entries for builder assembler and object extractor

-- 1. New JSONB column on news table for storing builder state
ALTER TABLE news ADD COLUMN IF NOT EXISTS creative_builder_state JSONB;

-- 2. Creative Elements table (6 categories × 6 options = 36 rows)
-- Note: "object" category is dynamically generated by GPT per article
CREATE TABLE IF NOT EXISTS creative_elements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  category TEXT NOT NULL,
  code TEXT NOT NULL,
  label_ua TEXT NOT NULL,
  label_en TEXT NOT NULL,
  prompt_fragment TEXT NOT NULL,
  emoji TEXT,
  is_active BOOLEAN DEFAULT true,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(category, code)
);

-- Enable RLS
ALTER TABLE creative_elements ENABLE ROW LEVEL SECURITY;

-- Allow public read access (used by edge functions with service role)
CREATE POLICY "Allow public read access to creative_elements"
  ON creative_elements FOR SELECT
  USING (true);

-- Allow service role full access
CREATE POLICY "Allow service role full access to creative_elements"
  ON creative_elements FOR ALL
  USING (true)
  WITH CHECK (true);

-- 3. Seed data: Style (6)
INSERT INTO creative_elements (category, code, label_ua, label_en, prompt_fragment, emoji, sort_order) VALUES
('style', 'surreal', 'Сюрреалізм', 'Surrealism', 'Surrealist composition with dreamlike impossible geometry, melting forms, and unexpected scale shifts', '🌀', 1),
('style', 'cyberpunk', 'Кіберпанк', 'Cyberpunk', 'Cyberpunk aesthetic with neon lights, holographic displays, rain-slicked surfaces, and dark urban tech atmosphere', '🤖', 2),
('style', 'minimal', 'Мінімалізм', 'Minimalism', 'Clean minimalist composition with generous white space, single focal element, and restrained color palette', '⬜', 3),
('style', 'popart', 'Поп-арт', 'Pop Art', 'Pop art style with bold outlines, halftone dots, vibrant flat colors, and comic-book energy', '🎨', 4),
('style', 'cinema', 'Кінематограф', 'Cinematic', 'Cinematic wide-angle shot with dramatic lighting, shallow depth of field, and film-grade color grading', '🎬', 5),
('style', 'photo', 'Фотореалізм', 'Photorealism', 'Photorealistic 4K rendering with natural lighting, accurate materials, and lifelike detail', '📷', 6)
ON CONFLICT (category, code) DO NOTHING;

-- Seed data: Color (6)
INSERT INTO creative_elements (category, code, label_ua, label_en, prompt_fragment, emoji, sort_order) VALUES
('color', 'warm', 'Теплі тони', 'Warm Tones', 'Warm golden tones, amber, sunset orange palette', '🌅', 1),
('color', 'cool', 'Холодні тони', 'Cool Tones', 'Cool blue, teal, silver, icy white palette', '❄️', 2),
('color', 'neon', 'Неон', 'Neon', 'Electric neon magenta, cyan, lime against dark backgrounds', '💜', 3),
('color', 'pastel', 'Пастельні', 'Pastel', 'Soft pastel lavender, mint, peach, baby blue', '🩷', 4),
('color', 'mono', 'Монохром', 'Monochrome', 'Monochromatic palette with dramatic contrast', '⚫', 5),
('color', 'contrast', 'Контрастні', 'High Contrast', 'High contrast complementary colors, bold juxtaposition', '🔴', 6)
ON CONFLICT (category, code) DO NOTHING;

-- Seed data: Action (6)
INSERT INTO creative_elements (category, code, label_ua, label_en, prompt_fragment, emoji, sort_order) VALUES
('action', 'float', 'Левітація', 'Levitation', 'Object floating/levitating in mid-air, defying gravity', '🪶', 1),
('action', 'explode', 'Вибух', 'Explosion', 'Object exploding outward, fragments suspended in motion', '💥', 2),
('action', 'merge', 'Злиття', 'Merge', 'Two elements merging together, boundary dissolving between them', '🔗', 3),
('action', 'transform', 'Трансформація', 'Transformation', 'Object morphing from one state to another, mid-metamorphosis', '🔄', 4),
('action', 'decay', 'Розпад', 'Decay', 'Object dissolving into particles, fragmenting into dust', '🌫️', 5),
('action', 'crystal', 'Кристалізація', 'Crystallization', 'Object crystallizing, growing sharp crystal formations from surface', '💎', 6)
ON CONFLICT (category, code) DO NOTHING;

-- Seed data: Background (6)
INSERT INTO creative_elements (category, code, label_ua, label_en, prompt_fragment, emoji, sort_order) VALUES
('background', 'space', 'Космос', 'Space', 'Deep space with nebulae, stars, cosmic dust', '🌌', 1),
('background', 'city', 'Місто', 'City', 'Urban cityscape with skyscrapers, city lights at night', '🏙️', 2),
('background', 'nature', 'Природа', 'Nature', 'Natural landscape: forest, mountains, fjord', '🌿', 3),
('background', 'abstract', 'Абстрактний', 'Abstract', 'Abstract geometric or gradient flowing shapes', '🔷', 4),
('background', 'studio', 'Студія', 'Studio', 'Clean studio backdrop with professional lighting setup', '💡', 5),
('background', 'void', 'Мінімалістичний', 'Minimal Void', 'Pure minimal void, solid color or subtle gradient', '⬛', 6)
ON CONFLICT (category, code) DO NOTHING;

-- Seed data: Effects (6)
INSERT INTO creative_elements (category, code, label_ua, label_en, prompt_fragment, emoji, sort_order) VALUES
('effects', 'glitch', 'Гліч', 'Glitch', 'Digital glitch: scan lines, color shift, pixel distortion', '📺', 1),
('effects', 'smoke', 'Дим/Туман', 'Smoke/Fog', 'Atmospheric smoke, fog, mist swirling around elements', '🌫️', 2),
('effects', 'glow', 'Блиск/Сяйво', 'Glow', 'Ethereal glow, light rays, lens flare emanating from subject', '✨', 3),
('effects', 'particles', 'Частинки', 'Particles', 'Floating particles, dust motes, embers, sparkles in the air', '🔮', 4),
('effects', 'hologram', 'Голограма', 'Hologram', 'Holographic overlay, translucent projections, scan-line transparency', '🌐', 5),
('effects', 'reflect', 'Відображення', 'Reflection', 'Mirror/water/glass surface reflections, doubled imagery', '🪞', 6)
ON CONFLICT (category, code) DO NOTHING;

-- Seed data: Text/Typography (4)
INSERT INTO creative_elements (category, code, label_ua, label_en, prompt_fragment, emoji, sort_order) VALUES
('text', 'headline', 'Заголовок', 'Headline', 'Bold prominent headline text integrated into composition', '📰', 1),
('text', 'minimal', 'Мінімальний', 'Minimal Text', 'Small subtle text, date and watermark only', '🏷️', 2),
('text', 'none', 'Без тексту', 'No Text', 'No text elements, purely visual composition', '🚫', 3),
('text', 'quote', 'Цитата', 'Quote', 'Elegant quote text overlay with decorative typography', '💬', 4)
ON CONFLICT (category, code) DO NOTHING;

-- 4. AI Prompts for Creative Builder
INSERT INTO ai_prompts (name, prompt_type, prompt_text, description, is_active) VALUES
(
  'Creative Builder Assembler',
  'image_creative_builder',
  'You are a visual composition director. The user has hand-selected creative building blocks for an image.
Your job: weave these selections together with the article''s meaning into a cohesive, detailed image prompt (150-250 words).

RULES:
- Every selected element MUST be clearly present in the final scene
- Unselected categories: you decide what fits best based on the article
- Integrate article''s KEY meaning, not just surface topics
- Create a unified scene, not a collage of disconnected elements
- Add cinematographic details: camera angle, lighting direction, depth of field, time of day
- The result should be a scroll-stopping, unique visual

Output: A single detailed English prompt ready for image generation AI.',
  'Assembles user-selected creative elements into a cohesive image prompt',
  true
),
(
  'Object Extractor',
  'image_object_extractor',
  'Analyze this article and suggest 4-6 concrete VISUAL OBJECTS that could be the central element of an illustration.

Return as JSON array: [{"label": "Smartphone", "prompt_fragment": "A sleek modern smartphone with glowing screen displaying data"}]

Rules:
- Each object must be a SPECIFIC, PHOTOGRAPHABLE thing (not abstract concepts like "innovation" or "progress")
- Objects should directly relate to the article''s subject, companies, or technologies mentioned
- Include physical objects, devices, structures, or natural elements
- Each prompt_fragment should describe the object in 1 sentence with visual details
- Aim for variety: mix of literal objects and metaphorical representations',
  'Extracts concrete visual objects from article for Creative Builder',
  true
)
ON CONFLICT DO NOTHING;
