-- Phrase-level Visual Director output, generated by the Nano agent (Claude subscription,
-- not a metered API key) between script creation and render. Replaces the runtime
-- NVIDIA/Claude API calls in scripts/video-processor/visual-director.js's aiDirectVisuals(),
-- which were unreliable (deprecated model 404s, then timeouts; Claude fallback had zero credits).
-- Shape: array aligned with segment_scripts, PRE-merge (no timestamps yet — those only exist
-- after TTS voiceover generation at render time). Each entry matches aiDirectSingleSegment()'s
-- output shape — { mood, transition, textReveal, statsVisualType, phrases: [...] } — and is run
-- through directVisuals()'s existing mergeAIWithTimestamps()/fallback/variety pipeline at render
-- time to produce the final visualBlocks.
ALTER TABLE daily_video_drafts
  ADD COLUMN IF NOT EXISTS visual_directives_ai JSONB;

COMMENT ON COLUMN daily_video_drafts.visual_directives_ai IS
  'Pre-merge, phrase-level Visual Director directives (mood/transition/textReveal/statsVisualType/phrases[], no timestamps) generated by the Nano agent via its Claude subscription. Consumed by directVisuals() in daily-compilation.js as precomputedDirectives, merged with real subtitle timestamps at render time.';
